//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.factura = new HashSet<factura>();
            this.pedido = new HashSet<pedido>();
        }
    
        public int clienteID { get; set; }
        [DisplayName("Metodo de pago")]
        public int metodoPagoID { get; set; }
        public string nombre { get; set; }
        public string pais { get; set; }
        public string direccion { get; set; }
        [DisplayName("Codigo postal")]
        public string codigoPostal { get; set; }
        public Nullable<int> telefono { get; set; }
        [DisplayName("Limite de credito")]
        public Nullable<double> limiteCredito { get; set; }
        [DisplayName("Direccion fisica")]
        public string direccionFisica { get; set; }
        [EmailAddress]
        public string correo { get; set; }
        [DisplayName("Fecha Inicio")]
        public Nullable<System.DateTime> fechaInicio { get; set; }
    
        public virtual metodoPago metodoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
