//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.pedido = new HashSet<pedido>();
            this.empleado1 = new HashSet<empleado>();
            this.empleado2 = new HashSet<empleado>();
        }
    
        public int empleadoID { get; set; }
        public string nombre { get; set; }
        [DisplayName("Primer apellido")]
        public string apellido1 { get; set; }
        [DisplayName("Segundo apellido")]
        public string apellido2 { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public string residencia { get; set; }
        [StringLength(4, MinimumLength = 4)]
        public string puesto { get; set; }
        [DisplayName("Fecha de nacimiento")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        [DisplayName("Fecha de ingreso")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        [DisplayName("Fecha de retiro")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaRetiro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado2 { get; set; }
    }
}
