//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.cuentaPorCobrar = new HashSet<cuentaPorCobrar>();
            this.lineaFactura = new HashSet<lineaFactura>();
        }

        [DisplayName("Factura")]
        public int facturaID { get; set; }
        [Required]
        [DisplayName("Cliente")]
        public int clienteID { get; set; }
        [DisplayName("Fecha creacion")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        [DisplayName("Fecha de vencimiento")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        [DisplayName("Direccion de entrega")]
        public string direccionEntrega { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentaPorCobrar> cuentaPorCobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineaFactura> lineaFactura { get; set; }
    }
}
