//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class lineaPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lineaPedido()
        {
            this.lineaFactura = new HashSet<lineaFactura>();
        }

        [DisplayName("Linea pedido")]
        public int lineaPedidoID { get; set; }
        [Required]
        [DisplayName("Pedido")]
        public string pedidoID { get; set; }
        [Required]
        [DisplayName("Producto")]
        public int productoID { get; set; }
        [Required]
        public Nullable<int> cantidad { get; set; }
        [DisplayName("Precio de venta")]
        public Nullable<double> precioVenta { get; set; }
        [Required]
        public Nullable<double> descuento { get; set; }
        public Nullable<double> impuesto { get; set; }
        [DisplayName("Precio total")]
        public Nullable<double> precioTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineaFactura> lineaFactura { get; set; }
        public virtual pedido pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
