//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class lineaFactura
    {
        [DisplayName("Linea factura")]
        public int lineaFacturaID { get; set; }
        [Required]
        [DisplayName("Factura")]
        public int facturaID { get; set; }
        [Required]
        [DisplayName("Linea Pedido")]
        public int lineaPedidoID { get; set; }
        [Required]
        [DisplayName("Cantidad facturada")]
        public Nullable<int> cantidadFacturada { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> subtotal { get; set; }
        [DisplayName("Total descuento")]
        public Nullable<double> totalDescuento { get; set; }
        [DisplayName("Linea Impuesto")]
        public Nullable<double> totalImpuesto { get; set; }
        [DisplayName("Total a pagar")]
        public Nullable<double> totalPagar { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual lineaPedido lineaPedido { get; set; }
    }
}
