//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventasP2Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.lineaPedido = new HashSet<lineaPedido>();
        }
        
        [DisplayName("Pedido")]
        public string pedidoID { get; set; }
        [Required]
        [DisplayName("Empleado")]
        public int empleadoID { get; set; }
        [Required]
        [DisplayName("Cliente")]
        public int clienteID { get; set; }
        [DisplayName("Fecha de creacion")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        [DisplayName("Fecha de entrega")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string estado { get; set; }
        [DisplayName("Descripcion estado")]
        public string descripcionEstado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lineaPedido> lineaPedido { get; set; }
    }
}
